"""Failing tests for FNDN-02 (parse consolidation) and FNDN-04 (ingest-time normalization).

These tests are RED by design — they test behavior that will only exist after
Plans 03 and 04 implement parse_single_file_bytes() in core/ingest.py.

Wave 0 scaffold: written before any implementation.
"""

import io
import pytest
import pandas as pd
import openpyxl


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_minimal_xlsx_bytes(extra_columns=None, description_value=None):
    """Build an in-memory XLSX with the ANCHOR_COLUMN and a minimal set of
    REQUIRED_COLUMNS so the header-row detection logic can find it.

    Returns a BytesIO ready to pass to parse_single_file_bytes().
    """
    from core.ingest import REQUIRED_COLUMNS, ANCHOR_COLUMN

    wb = openpyxl.Workbook()
    ws = wb.active

    # Row 1: some junk header (simulates CDARS metadata rows before the real header)
    ws.append(["Report generated by CDARS system", None, None])

    # Row 2: the actual CDARS column header row (contains ANCHOR_COLUMN)
    header_row = list(REQUIRED_COLUMNS)
    if extra_columns:
        header_row += extra_columns
    ws.append(header_row)

    # Row 3: one data row
    data_row = ["P0001"] + ["value"] * (len(header_row) - 1)
    if description_value is not None:
        # Put the value in the "Principal Diagnosis Description (HAMDCT)" column
        try:
            idx = header_row.index("Principal Diagnosis Description (HAMDCT)")
            data_row[idx] = description_value
        except ValueError:
            pass
    ws.append(data_row)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# FNDN-02: parse_single_file_bytes is importable from core.ingest
# ---------------------------------------------------------------------------

class TestParseImportable:
    def test_page_delegates_to_core(self):
        """parse_single_file_bytes must be importable from core.ingest."""
        # This will raise ImportError if the function does not exist yet.
        from core.ingest import parse_single_file_bytes  # noqa: F401


# ---------------------------------------------------------------------------
# FNDN-02: parse_single_file_bytes(file_bytes, filename) behaviour
# ---------------------------------------------------------------------------

class TestParseSingleFileBytes:
    def test_parse_single_file_bytes_success(self):
        """A valid XLSX BytesIO returns (DataFrame, None)."""
        from core.ingest import parse_single_file_bytes

        buf = _make_minimal_xlsx_bytes()
        df, err = parse_single_file_bytes(buf, "test_file.xlsx")

        assert err is None, f"Expected no error, got: {err!r}"
        assert isinstance(df, pd.DataFrame), "Expected a DataFrame"
        assert "Reference Key" in df.columns, "DataFrame must contain 'Reference Key'"

    def test_parse_single_file_bytes_bad_file(self):
        """Garbage bytes return (None, non-empty error string)."""
        from core.ingest import parse_single_file_bytes

        garbage = io.BytesIO(b"\x00\x01\x02\x03garbage not an excel file")
        df, err = parse_single_file_bytes(garbage, "garbage.xlsx")

        assert df is None, "Expected None DataFrame for unparseable file"
        assert isinstance(err, str) and len(err) > 0, (
            "Expected a non-empty error string for unparseable file"
        )


# ---------------------------------------------------------------------------
# FNDN-04 (ingest-time): string columns normalised at parse time
# ---------------------------------------------------------------------------

class TestIngestNormalizesStringCols:
    def test_ingest_normalizes_string_cols(self):
        """An en-dash (U+2013) in a description column must be normalized to
        an ASCII hyphen '-' in the returned DataFrame."""
        from core.ingest import parse_single_file_bytes

        # "Self\u2013harm" contains an en-dash; after normalization it should
        # read "Self-harm"
        en_dash_value = "Self\u2013harm"
        buf = _make_minimal_xlsx_bytes(description_value=en_dash_value)
        df, err = parse_single_file_bytes(buf, "test_file.xlsx")

        assert err is None, f"Parse failed unexpectedly: {err!r}"
        assert df is not None

        desc_col = "Principal Diagnosis Description (HAMDCT)"
        assert desc_col in df.columns, f"Column {desc_col!r} missing from result"

        values = df[desc_col].tolist()
        assert any("Self-harm" in str(v) for v in values), (
            f"Expected en-dash normalized to ASCII hyphen in {values!r}"
        )
        assert not any("\u2013" in str(v) for v in values), (
            f"En-dash U+2013 should have been normalized away, got {values!r}"
        )
